name: Daily Tests

on:
  schedule:
    # Run at 2 AM every day
    - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Generate test report
      run: mvn surefire-report:report

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/site/surefire-report.html

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ Lukhanyohoho@outlook.com }}
        password: ${{ Luk@2018 }}
        subject: Daily Test Report
        body: Test report for ${{ github.repository }} on ${{ github.run_date }}
        to: your-email@example.com
        from: your-email@example.com
        attachments: target/site/surefire-report.html
